filters:
  - bsicons
  - callouty-theorem
  - collapse-callout
  - fontawesome
  # https://dixslyf.github.io/quarto-group-html-cell-outputs/configuration.html
  # if you want to exclude a cell's outputs from the filter, you need to specify group-outputs: false in its options
  - group-html-cell-outputs
  - include-code-files
  # Enable in Quarto doc if needed.
  # - language-name

project:
  type: website
  # https://quarto.org/docs/reference/projects/options.html#preview
  preview:
    browser: true
    port: 4200

website:
  title: "Ajay's blog"
  description: "This is Ajay Mehta's personal blog."
  site-url: "https://ajaymehta.netlify.app/"
  # https://quarto.org/docs/websites/website-navigation.html#reader-mode
  reader-mode: true
  repo-url: https://github.com/AjayKMehta/quarto-blog
  repo-actions: [source, issue]
  search:
    keyboard-shortcut: ["s", "/"]
    show-item-context: tree
  navbar:
    left:
      - text: About
        href: about.qmd
      - text: More
        menu:
        - text: Git tips
          href: git-tips.qmd
    right:
      - icon: github
        href: https://github.com/AjayKMehta
      - icon: rss
        href: index.xml
  # TODO: Update
  page-footer:
    left: "© 2025, Ajay Mehta. Built with [Quarto](https://quarto.org/)."
    right:
    - text: "License"
      href: LICENSE.md
    background: "#6fc0e2"
  cookie-consent:
    type: express
  open-graph: true

format:
  html:
    from: markdown+emoji
    anchor-sections: true
    mainfont: 'FiraCode Nerd Font Mono'
    font-family:
      - Source Sans Pro
      - 'FiraCode Nerd Font Mono'
      - Consolas
      - 'Courier New'
      - Roboto Regular
    code-annotations: hover
    code-tools: true
    code-fold: show
    code-overflow: scroll
    code-copy: true
    code-link: true
    highlight-style: ayu
    fig-responsive: true
    footnotes-hover: true
    code-block-border-left: "#4f6952"
    html-math-method: mathjax
    number-sections: false
    df-print: paged
    smooth-scroll: true
    respect-user-color-scheme: true
    theme:
      light: lumen
      dark: darkly
    css: styles.css

editor: source
