[default]
    check-filename = false
    unicode = true
    extend-ignore-identifiers-re = [
        "^([A-z]|[a-z])*Nd*",
        "^([A-z]|[a-z])*nd*",
        "activ*([A-z]|[a-z]|[0-9])*,",
    ]
    extend-ignore-re = [
        "(?s)^.*?`[^`]+`.*$",
        # Ignore current line
        ".*(#|--|//).*(spellchecker|typos):\\s?ignore[^\\n]*\\n",
        # Ignore next line
        ".*(#|--|//).*(spellchecker|typos):\\s?ignore-next-line[^\\n]*\\n[^\\n]*",
        # Line block
        "(?s)(#|--|//)\\s*(spellchecker|typos):off.*?\\n\\s*(#|--|//)\\s*(spellchecker|typos):on",
        "[A-Za-z]+://\\S{3,50}:(\\S{8,50})@[\\dA-Za-z#%&+./:=?_~-]+",
    ]

    [default.extend-words]
        "aiofiles" = "aiofiles"
        "aiohttp" = "aiohttp"
        "astype" = "astype"
        "deps" = "deps"
        "iloc" = "iloc"
        "mlxtend" = "mlxtend"
        "ndarray" = "ndarray"
        "networkx" = "networkx"
        "nums" = "nums"
        "sklearn" = "sklearn"
        "MOR" = "MOR"

[files]
    extend-exclude = [
        "typos.toml",
        "**/.git*",
        ".env",
        "**/*.csv",
        "**/*.js",
        "**/package-lock.json",
        "**/node-modules/**",
        "**/vscodeextension/**",
        "**/.git/objects/**",
        "**/.vscode/**",
        "**/.vscode-insiders/**",
        "**/.tmp-projections/**",
        "**/*.interactive",
    ]
